- name: copy logstash repo
  ansible.builtin.template:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo

- name: install logstash
  ansible.builtin.dnf:
    name: logstash
    state: installed

- name: copy logstash conf
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf


- name: start logstash service
  ansible.builtin.systemd_service:
    name: logstash.service
    state: started
    enabled: true




