- name: copy rysyslog file
  ansible.builtin.templates:
    src: rsyslog.conf
    dest: backend.conf

- name: start rysyslog service
  ansible.builtin.systemd_system:
    name: rsyslog
    state: started
    enabled: true
