- name: get vault secrets
  ansible.builtin.lineinfile:
    path: secrets.json
    line: "secrets":"{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token=hvs.T8WnPWmYmGZkPYlGAHXVmebk url=https://vault-internal.pdevops78.online:8200 validate_certs=False') }}"
    create: yes
