- name: vault secrets
  hosts: localhost
  tasks:
#    - name: get secrets
#      ansible.builtin.lineinfile:
#        path: ~/secrets.json
#        line: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/elastisearch token=hvs.T8WnPWmYmGZkPYlGAHXVmebk url=https://vault-internal.pdevops78.online:8200 validate_certs=False') }}"
#        create: yes

    - name: get app secrets
      ansible.builtin.lineinfile:
        path: ~/{{ item | split('/') | last }}.json
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'secret={{ item }} token=hvs.T8WnPWmYmGZkPYlGAHXVmebk url=https://vault-internal.pdevops78.online:8200 validate_certs=False') }}"
        create: yes
      loop:
        - common/data/elastisearch
        - common/data/{{project_name}}-{{component_name}}
        - common/data/rds

    - name: get json files from home directory
      ansible.builtin.shell:  for i in $(ls ~/*.json); do echo -n  "$(cat $i)"; done | sed -e 's/}{/, /g' > secrets.json

