- name: vault secrets
  hosts: localhost
  tasks:
    - name: get secrets
      ansible.builtin.lineinfile:
        path: secrets.json
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/elastisearch token=hvs.T8WnPWmYmGZkPYlGAHXVmebk url=https://vault-internal.pdevops78.online:8200 validate_certs=False') }}"
        create: yes

    - name: get app secrets
      ansible.builtin.lineinfile:
        path: app.json
        line: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=common/data/{{project_name}}-{{component_name}} token=hvs.T8WnPWmYmGZkPYlGAHXVmebk url=https://vault-internal.pdevops78.online:8200 validate_certs=False') }}"
        create: yes
