- name: Install nginx package
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: copy expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import code commonly
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req.yml

- name: restart nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    daemon-reload: yes
    enabled: yes

- name: Import new relic code
  ansible.builtin.import_role:
    name: newrelic
    tasks_from: nginx.yml




