- name: set sudo prompt
  ansible.builtin.shell: set-prompt {{component}}

- name: Import code commonly
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter.yml

- name: Import logstash code
  ansible.builtin.import_role:
    name: logstash
    tasks_from: main.yml

- name: Import rsyslog code
  ansible.builtin.import_role:
    name: rsyslog
    tasks_from: main.yml





