- name: clean the code
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Make a directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Download artifactory
  ansible.builtin.get_url:
    url: http://{{artifactory_user}}:{{artifactory_password}}@13.222.138.152:8081/artifactory/expense-frontend/{{app_version}}.zip
    dest: /tmp
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Unarchive {{component}}
  ansible.builtin.unarchive:
    src: /tmp
    dest: "{{ app_loc }}"
    remote_src: yes
    owner: "{{ app_user }}"
    group: "{{ app_user }}"


# http://{{artifactory_user}}:{{artifactory_password}}@artifactory-internal.pdevops78.online:8081/artifactory/expense-{{ component }}/{{APP_VERSION}}.zip
