- name: clean the code
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Make a directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"


# - name: Download and Extract App Content
#   ansible.builtin.unarchive:
#     src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
#     dest: "{{ app_loc }}"
#     remote_src: yes
#     owner: "{{app_user}}"
#     group: "{{app_user}}"

- name: Download artifactory
  ansible.builtin.get_url:
    url: http://admin:Artifact123@artifact-internal.pdevops78.online:8081/artifactory/expense-{{component}}/1.0.zip
    dest: /tmp


- name: Unarchive artifactory
  ansible.builtin.unarchive:
    src: /tmp/1.0.zip
    dest: "{{ app_loc }}"
    remote_src: yes
    owner: "{{ app_user }}"
    group: "{{ app_user }}"



