input{
file{
path => "{{ frontend_log_file }}"
}
}

output {
elasticsearch {
hosts => "http://54.196.241.174:9200"
data_stream => "auto"
user => "elastic"
password => "sT1tVagtnU5uO0DfRjxO"
index => "frontend-log-%{+yyyy.MM.dd}"
}
}