input{
file{
path => "{{ frontend_log_file }}"
}
}

output {
   elasticsearch {
       hosts => "https://172.31.90.28:9200"
       user => "elastic"
       password => "JM5x_SihF6Ba*P0j=iPR"
       index => "frontend-log-%{+yyyy.MM.dd}"
}
}


